import type { BigFiveQuestion } from "./types.ts";

// Source IDs and scoring keys are preserved. Chinese is a locally adapted,
// unvalidated translation; scores are not population percentiles.
// Full provenance and license notices: /licenses/bigfive-sources.txt
export const questions50: readonly BigFiveQuestion[] = [
  {
    id: "1",
    sourceEnglish: "Am the life of the party",
    domain: "E",
    reverse: false,
    text: "我常是聚会中活跃气氛的人。",
  },
  {
    id: "2",
    sourceEnglish: "Feel little concern for others",
    domain: "A",
    reverse: true,
    text: "我很少关心别人。",
  },
  {
    id: "3",
    sourceEnglish: "Am always prepared",
    domain: "C",
    reverse: false,
    text: "我总会做好准备。",
  },
  {
    id: "4",
    sourceEnglish: "Get stressed out easily",
    domain: "N",
    reverse: false,
    text: "我很容易感到压力。",
  },
  {
    id: "5",
    sourceEnglish: "Have a rich vocabulary",
    domain: "O",
    reverse: false,
    text: "我的词汇量丰富。",
  },
  {
    id: "6",
    sourceEnglish: "Don't talk a lot",
    domain: "E",
    reverse: true,
    text: "我不太多话。",
  },
  {
    id: "7",
    sourceEnglish: "Am interested in people",
    domain: "A",
    reverse: false,
    text: "我对他人感兴趣。",
  },
  {
    id: "8",
    sourceEnglish: "Leave my belongings around",
    domain: "C",
    reverse: true,
    text: "我会随手乱放自己的物品。",
  },
  {
    id: "9",
    sourceEnglish: "Am relaxed most of the time",
    domain: "N",
    reverse: true,
    text: "我大多数时候都很放松。",
  },
  {
    id: "10",
    sourceEnglish: "Have difficulty understanding abstract ideas",
    domain: "O",
    reverse: true,
    text: "我觉得抽象的概念难以理解。",
  },
  {
    id: "11",
    sourceEnglish: "Feel comfortable around people",
    domain: "E",
    reverse: false,
    text: "我和他人相处时感觉自在。",
  },
  {
    id: "12",
    sourceEnglish: "Insult people",
    domain: "A",
    reverse: true,
    text: "我会说侮辱别人的话。",
  },
  {
    id: "13",
    sourceEnglish: "Pay attention to details",
    domain: "C",
    reverse: false,
    text: "我注重细节。",
  },
  {
    id: "14",
    sourceEnglish: "Worry about things",
    domain: "N",
    reverse: false,
    text: "我会为各种事情担忧。",
  },
  {
    id: "15",
    sourceEnglish: "Have a vivid imagination",
    domain: "O",
    reverse: false,
    text: "我的想象力很生动。",
  },
  {
    id: "16",
    sourceEnglish: "Keep in the background",
    domain: "E",
    reverse: true,
    text: "我倾向于待在不显眼的位置。",
  },
  {
    id: "17",
    sourceEnglish: "Sympathize with others' feelings",
    domain: "A",
    reverse: false,
    text: "我能体谅别人的感受。",
  },
  {
    id: "18",
    sourceEnglish: "Make a mess of things",
    domain: "C",
    reverse: true,
    text: "我会把东西弄得乱七八糟。",
  },
  {
    id: "19",
    sourceEnglish: "Seldom feel blue",
    domain: "N",
    reverse: true,
    text: "我很少感到低落。",
  },
  {
    id: "20",
    sourceEnglish: "Am not interested in abstract ideas",
    domain: "O",
    reverse: true,
    text: "我对抽象的概念不感兴趣。",
  },
  {
    id: "21",
    sourceEnglish: "Start conversations",
    domain: "E",
    reverse: false,
    text: "我会主动开启交谈。",
  },
  {
    id: "22",
    sourceEnglish: "Am not interested in other people's problems",
    domain: "A",
    reverse: true,
    text: "我对别人的烦恼不感兴趣。",
  },
  {
    id: "23",
    sourceEnglish: "Get chores done right away",
    domain: "C",
    reverse: false,
    text: "我会立即完成日常杂事。",
  },
  {
    id: "24",
    sourceEnglish: "Am easily disturbed",
    domain: "N",
    reverse: false,
    text: "我很容易心烦。",
  },
  {
    id: "25",
    sourceEnglish: "Have excellent ideas",
    domain: "O",
    reverse: false,
    text: "我有很棒的点子。",
  },
  {
    id: "26",
    sourceEnglish: "Have little to say",
    domain: "E",
    reverse: true,
    text: "我没有太多话要说。",
  },
  {
    id: "27",
    sourceEnglish: "Have a soft heart",
    domain: "A",
    reverse: false,
    text: "我心肠软。",
  },
  {
    id: "28",
    sourceEnglish: "Often forget to put things back in their proper place",
    domain: "C",
    reverse: true,
    text: "我经常忘记把物品放回原处。",
  },
  {
    id: "29",
    sourceEnglish: "Get upset easily",
    domain: "N",
    reverse: false,
    text: "我很容易感到不快。",
  },
  {
    id: "30",
    sourceEnglish: "Do not have a good imagination",
    domain: "O",
    reverse: true,
    text: "我的想象力不太好。",
  },
  {
    id: "31",
    sourceEnglish: "Talk to a lot of different people at parties",
    domain: "E",
    reverse: false,
    text: "聚会时，我会与许多不同的人交谈。",
  },
  {
    id: "32",
    sourceEnglish: "Am not really interested in others",
    domain: "A",
    reverse: true,
    text: "我对他人并没有多少兴趣。",
  },
  {
    id: "33",
    sourceEnglish: "Like order",
    domain: "C",
    reverse: false,
    text: "我喜欢井然有序。",
  },
  {
    id: "34",
    sourceEnglish: "Change my mood a lot",
    domain: "N",
    reverse: false,
    text: "我的心情经常改变。",
  },
  {
    id: "35",
    sourceEnglish: "Am quick to understand things",
    domain: "O",
    reverse: false,
    text: "我能很快理解事情。",
  },
  {
    id: "36",
    sourceEnglish: "Don't like to draw attention to myself",
    domain: "E",
    reverse: true,
    text: "我不喜欢引起别人对我的注意。",
  },
  {
    id: "37",
    sourceEnglish: "Take time out for others",
    domain: "A",
    reverse: false,
    text: "我会抽出时间帮助或陪伴别人。",
  },
  {
    id: "38",
    sourceEnglish: "Shirk my duties",
    domain: "C",
    reverse: true,
    text: "我会逃避自己的职责。",
  },
  {
    id: "39",
    sourceEnglish: "Have frequent mood swings",
    domain: "N",
    reverse: false,
    text: "我的情绪经常起伏。",
  },
  {
    id: "40",
    sourceEnglish: "Use difficult words",
    domain: "O",
    reverse: false,
    text: "我会使用较难的词语。",
  },
  {
    id: "41",
    sourceEnglish: "Don't mind being the center of attention",
    domain: "E",
    reverse: false,
    text: "我不介意成为大家关注的焦点。",
  },
  {
    id: "42",
    sourceEnglish: "Feel others' emotions",
    domain: "A",
    reverse: false,
    text: "我能感受到别人的情绪。",
  },
  {
    id: "43",
    sourceEnglish: "Follow a schedule",
    domain: "C",
    reverse: false,
    text: "我会按照日程安排做事。",
  },
  {
    id: "44",
    sourceEnglish: "Get irritated easily",
    domain: "N",
    reverse: false,
    text: "我很容易烦躁。",
  },
  {
    id: "45",
    sourceEnglish: "Spend time reflecting on things",
    domain: "O",
    reverse: false,
    text: "我会花时间反思各种事情。",
  },
  {
    id: "46",
    sourceEnglish: "Am quiet around strangers",
    domain: "E",
    reverse: true,
    text: "在陌生人面前，我比较安静。",
  },
  {
    id: "47",
    sourceEnglish: "Make people feel at ease",
    domain: "A",
    reverse: false,
    text: "我能让别人感到自在。",
  },
  {
    id: "48",
    sourceEnglish: "Am exacting in my work",
    domain: "C",
    reverse: false,
    text: "我对自己的工作要求严格。",
  },
  {
    id: "49",
    sourceEnglish: "Often feel blue",
    domain: "N",
    reverse: false,
    text: "我经常感到低落。",
  },
  {
    id: "50",
    sourceEnglish: "Am full of ideas",
    domain: "O",
    reverse: false,
    text: "我有很多点子。",
  },
];
